name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # 必須 fetch 完整歷史
          lfs: true           # 改成 true

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global http.postBuffer 524288000
          git push --force https://mikekwwong:${HF_TOKEN}@huggingface.co/spaces/mikekwwong/Hermes_AI main
