name: Sync to Hugging Face Hub

on:
  push:
    branches: [ main ]  # 监听 main 分支的推送

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true    # 确保大文件也被正确拉取
      - name: Push to Hugging Face Space
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: mikekwwong/Hermes_AI # 需替换
          hf_token: ${{ secrets.HF_TOKEN }}
